id: P30D2C380
initial_creation_type: ocr
source_metadata:
  volumes:
    be041bbedc01495d801eed5642d3659f:
      base_file: v055.txt
      image_group_id: I1PD95900
      title: འཕགས་པ་ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་མ་བསྡུས་པའི་ཚིག་ལེའུར་བྱས་པ།
      total_pages: 1470
      volume_number: 55
